# Generated by Django 2.2.4 on 2021-10-02 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_wishes', '0002_wish_granted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wish',
            name='granted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_wishes.Granted'),
        ),
    ]
